### ISSUE TITLE
Compatibility with the new CrudField JS library?

### ISSUE THREAD

**Issue by fronbow** [DigitallyHappy/toggle-field-for-backpack#10]
Hi

With the awesome new CrudField JS library now live, is there any chance of getting this to play nicely with the new functionality?

Cheers

**Comment by adrienne** [comment]
Yeah, I need this too!

**Comment by tabacitu** [comment]
Yes totally. We're on it, putting it on "This week", thanks!

**Comment by pxpm** [comment]
Hello guys. This time will be me bearing the bad news.

Unfortunatelly me and @tabacitu discussed this a little bit more and decided that **we should not do it**. 
The main reason is because this is: `a CSS-only solution, so it has zero external dependencies and zero javascript` and for it to work with JS API guess what? It needed some JS solution. 

I've done it, and only later realised that adding JS support would be changing the scope of this field, so if anybody needs the field with JS API support can get it from here: [toggle with js api](https://gist.github.com/pxpm/5dffa635c5d9d16c4c9942813a195c6d)

I've even tested it, so here it goes how I made it work: `crud.field('agreed').onChange(function(field) { let value = Boolean(parseInt(field.input.value)); crud.field('some_other_field').show(value) })`

We have always wanted to add more features in this field like `switching color`, `adding labels` etc, so we will be releasing in the next weeks a ~~pro field~~ (we talked after I wrote this and this is going to be a free field) that is intended to replace this one with a more flexible and configurable field that fully supports JS API.

Stay tunned! 👍

**Comment by fronbow** [comment]
Cheers for this guys, it's nice to know the pro version is imminent :) and for your interim option Pedro

**Comment by tabacitu** [comment]
Update: and this time it's GOOD news 😅

We've decided to add the new `switch` field to Backpack\CRUD. That means it'll be FREE and baked-in, so it'll be a no-brainer, 100% replacement for this addon. Toggle = switch on steroids. 

That's the fair thing to do, and it fixes ALL problems. (not world peace though, still working on that one)

So I'm going to close this issue, as we're not going to add CrudField JS library support to `toggle` - no point in doing that. But in 1-2 weeks we ARE launching `switch`, bundled with Backpack v5, free for everybody. To use it, you'll just have to 
- change the field type from "toggle" to "switch"
- remove the field namespace

🎉
