### ISSUE TITLE
Support for columns

### ISSUE THREAD

**Issue by lisotton** [DigitallyHappy/toggle-field-for-backpack#6]
Hi, 

I'm still analyzing if Backpack is a fit for a project that I'm working on. I did not find anything similar with `switch` present in Laravel-admin: https://laravel-admin.org/docs/en/model-grid-inline-edit#Switch

It would be nice to have the field provided by this package also available for columns and with the possibility to apply the change once the user toggle the value.

Best regards,

**Comment by tabacitu** [comment]
Hi @lisotton . 

I agree, it'd be useful in some projects to have a `toggle` column that actually toggles an attribute. We haven't added "active columns" (aka "fields as columns") in Backpack because supporting ONE column is super-easy, but supporting ALL fields as column, with the underlying saving logic to "just work"... that's a monster of an endeavour.

To create what I understand you need in Backpack, you'll have to:
- [create a custom column type](https://backpackforlaravel.com/docs/4.1/crud-columns#creating-a-custom-column-type-1), which is as simple as creating `resources/views/vendor/backpack/crud/columns/toggle`;
- add the JS logic you need, to make an AJAX call to an endpoint you control; you can use [the delete button](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/buttons/delete.blade.php) as an example, there's a trick there to push the JS in the `after_scripts` section;
- create the route and controller that processes that request, toggles the attribute and returns a response; 
- (improvement idea) even better, you could [create an operation](https://backpackforlaravel.com/docs/4.1/crud-operations#creating-a-new-operation-with-no-interface), something like `ToggleAttributeOperation`; it's super-easy, and it'd allow you to re-use this operation across as many CrudControllers as you want, to easily add `toggle` columns without having to re-code the route/controller/etc; 

Since this is outside the scope of this package, I'm going to try to move the issue from [digitallyhappy/toggle-field-for-backpack](https://github.com/DigitallyHappy/toggle-field-for-backpack/issues/6) in our `addons` repo. I think this could be a really cool addon, if someone builds it. @lisotton if you do decide to use Backpack, and end up building the above (or similar) let me know, I'll gladly help you turn it into an addon for everybody else to reuse your code too.

Cheers!

PS. I've copy-pasted the answer above in the other repo, and I'll be closing this issue here and keep it open there.
