### ISSUE TITLE
Toggle not work inside a repeatable field

### ISSUE THREAD

**Issue by gcasaroseisnet** [DigitallyHappy/toggle-field-for-backpack#7]
setting a toggle type field inside a repeatable always save it as true but not show the toggle as selected

**Comment by tabacitu** [comment]
Thanks @gcasaroseisnet - didn't know that. I've just added a sister-issue in https://github.com/Laravel-Backpack/CRUD/issues/3924 so that we take care of it right away, in Backpack 4.1.

Cheers!

**Comment by pxpm** [comment]
Hey guys!

Thanks for raising the issue @gcasaroseisnet !

Unfortunatelly there is not much we can do to make the field work inside repeatable in version 4.1. But I have good news, 4.2 is really close to be lunched and this is fixed by: https://github.com/Laravel-Backpack/CRUD/pull/3905

I've just tested and everything works as expected using that branch.

I am going to close this since we already have the fix for it!

Thanks again,
Pedro

**Comment by tabacitu** [comment]
Thanks for the info @pxpm . Until then @gcasaroseisnet please use the `checkbox` field - that definitely works inside `repeatable`.
